-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3KQGkKg0+ZutR+e3
lxkYNjsQoQqllDKi9bGXjaTGpf+gCgYIKoZIzj0DAQehRANCAAQGNyqh7kdYWaxn
5/1v31Fs/u7iXvfjDsRH1WAHPh9+Q85B8uHUHsQ/s/YatK5gBf8xcMeAnpwA3VoQ
NYWREF25
-----END PRIVATE KEY-----