name: flutter_survey
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^4.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  japx: ^2.0.4
  json_annotation: ^4.6.0
  package_info_plus: ^1.4.2
  page_view_dot_indicator: ^2.0.1
  permission_handler: ^10.2.0
  retrofit: '>=4.0.0 <5.0.0'
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  email_validator: '^2.1.16'
  flutter_secure_storage: ^8.0.0
  collection: ^1.16.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mockito: ^5.2.0
  retrofit_generator: '>=5.0.0 <6.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Neuzeit
      fonts:
        - asset: assets/fonts/Neuzeit-Regular.otf
          weight: 400
        - asset: assets/fonts/Neuzeit-Bold.otf
          weight: 800
